[package]
name = "svgbob"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
description = "Transform your ascii diagrams into happy little SVG"
repository = "https://github.com/ivanceras/svgbobrus"
keywords = ["ascii", "svg", "convert"]

[dependencies]
svg = "0.5"
