[package]
name = "svgbob"
version = "0.2.8"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
description = "Transform your ascii diagrams into happy little SVG"
repository = "https://github.com/ivanceras/svgbobrus"
documentation = "https://docs.rs/svgbob"
keywords = ["ascii","plain","text", "svg", "bob"]
license = "Apache-2.0"

[dependencies]
svg = "0.5"
unicode-width = "0.1"
pom = "1.0.1"


[lib]
[dev-dependencies]
handlebars = "0.21"
pretty_assertions = "0.2"
sys-info = "0.5.1"
